### ISSUE TITLE
Refactoring and testing

### ISSUE THREAD

**Issue by alsiola** [alsiola/pm2-explorer#9]
Currently the code is functional but there poorly structured. The PM2 classes are responsible for both interacting with PM2 and displaying views - poor separation of concerns. There are several easy wins here, but it is also worth looking at other VSCode extensions and following any established conventions around program structure to make future collaboration easier.

There are currently no unit tests. These should probably focus on ensuring we correctly handle error conditions when PM2 is inaccessible or responds unexpectedly.

**Comment by alsiola** [comment]
Code structure improvments in #10

**Comment by prashanthr** [comment]
@alsiola Cool extension - great work so far! I'm quite familiar with PM2 and I would love to help with the code by adding new features and/or making improvements. Please do let me know how I can help in my free time.

**Comment by alsiola** [comment]
Thanks for offering your time and knowledge @prashanthr , it's really appreciated. So far I have implemented things that I would find useful personally, but I'm aware that there are many other features offered by PM2 that I am unaware of. 

I would be really grateful if you had any insight into other features that you or others would find useful, or what improvements should be focussed on.  If there are any non-PM2 related improvements you think should be prioritised, e.g. non-English language support, then that would be great to know as well.

**Comment by prashanthr** [comment]
Here's what I have in mind at this time

**PM2 Features**
1) Human readable / relative uptime (10s/10m/10h instead of ms)
2) Configurable display of data points (id, status, uptime, instances, memory, cpu, mode, unstable restarts etc.) - Let the users choose what they want to see but provide defaults
3) Add options to delete, flush logs for a process (in addition to start, stop, reload) and same for global actions
4) Global action - Launch `pm2 monit` in the terminal

**Non PM2 Features**
1) Internationalization is a great feature! - It wouldn't be too hard to add this.
2) Search for a process (filter tree list by PM2 process name)
3) Actions can be added as icons to the process row instead of just in context menu via right click

**Misc.**
1) Add tests
2) More Documentation

Let me know your thoughts. We could create a few issues and start working on them.

**Comment by alsiola** [comment]
They all sound like great ideas. I've created issues to track them (#15, #16, #17, #18, #19, #20) and created a project to track them. Once they are all complete then it would be worth releasing as a version 0.1.

If you would like to contribute to any of these issues then that would be fantastic, just go ahead and comment on the individual issues.

**Comment by alsiola** [comment]
I'm closing this issue now as I think everything mentioned above now has separate issues to track progress.

**Comment by prashanthr** [comment]
@alsiola Great! Thanks for creating those issues. I can certainly help with a few of these issues if not all. I'll post some comments soon.
